In [38]:
import pandas as pd

In [39]:
df=pd.read_csv('loan_risk_prediction_dataset.csv')

In [40]:
df.head()

,Age,Income,LoanAmount,CreditScore,YearsExperience,Gender,Education,City,EmploymentType,LoanApproved
0,56,48353.0,31258.0,675.0,20,Female,High School,Houston,Unemployed,0
1,69,57462.0,23262.0,586.0,6,Male,High School,San Francisco,Self-Employed,0
2,46,44219.0,26530.0,781.0,26,Male,PhD,Houston,Self-Employed,1
3,32,56307.0,11531.0,549.0,11,Male,NaN,New York,Unemployed,0
4,60,37034.0,27871.0,500.0,19,Female,High School,Chicago,Unemployed,0

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              5000 non-null   int64
 1   Income           4804 non-null   float64
 2   LoanAmount       5000 non-null   float64
 3   CreditScore      4806 non-null   float64
 4   YearsExperience  5000 non-null   int64
 5   Gender           5000 non-null   str
 6   Education        4802 non-null   str
 7   City             5000 non-null   str
 8   EmploymentType   5000 non-null   str
 9   LoanApproved     5000 non-null   int64
dtypes: float64(3), int64(3), str(4)
memory usage: 390.8 KB

In [42]:
df.isnull().sum()

Age                  0
Income             196
LoanAmount           0
CreditScore        194
YearsExperience      0
Gender               0
Education          198
City                 0
EmploymentType       0
LoanApproved         0
dtype: int64

In [43]:
def fill(df):
    for col in df.columns:
        if df[col].isnull().any():
            if df[col].dtype=='str':
                df[col]=df[col].fillna(df[col].mode()[0])
            else:
                df[col]=df[col].fillna(df[col].mean())
    return df

In [44]:
df=fill(df)
df.isnull().sum()

Age                0
Income             0
LoanAmount         0
CreditScore        0
YearsExperience    0
Gender             0
Education          0
City               0
EmploymentType     0
LoanApproved       0
dtype: int64

In [46]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
def encodla(df):
    for col in df.columns:
        if df[col].dtype=='str':
            if df[col].nunique()<=3:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=col),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [47]:
df=encodla(df)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Age                           5000 non-null   int64
 1   Income                        5000 non-null   float64
 2   LoanAmount                    5000 non-null   float64
 3   CreditScore                   5000 non-null   float64
 4   YearsExperience               5000 non-null   int64
 5   Education                     5000 non-null   int64
 6   City                          5000 non-null   int64
 7   LoanApproved                  5000 non-null   int64
 8   Gender_Female                 5000 non-null   int64
 9   Gender_Male                   5000 non-null   int64
 10  EmploymentType_Salaried       5000 non-null   int64
 11  EmploymentType_Self-Employed  5000 non-null   int64
 12  EmploymentType_Unemployed     5000 non-null   int64
dtypes: float64(3), int64(10)
memory usage: 507.9 KB

In [48]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
num_col=df.select_dtypes(include=['int64','float64']).columns.drop('LoanApproved')
df[num_col]=scaler.fit_transform(df[num_col])

In [49]:
df.head()

,Age,Income,LoanAmount,CreditScore,YearsExperience,Education,City,LoanApproved,Gender_Female,Gender_Male,EmploymentType_Salaried,EmploymentType_Self-Employed,EmploymentType_Unemployed
0,0.745098,0.506274,0.707338,0.683060,0.512821,0.333333,0.333333,0,1.0,0.0,0.0,0.0,1.0
1,1.000000,0.594817,0.570448,0.520947,0.153846,0.333333,1.000000,0,0.0,1.0,0.0,1.0,0.0
2,0.549020,0.466091,0.626395,0.876138,0.666667,1.000000,0.333333,1,0.0,1.0,0.0,1.0,0.0
3,0.274510,0.583590,0.369616,0.453552,0.282051,0.000000,0.666667,0,0.0,1.0,0.0,0.0,1.0
4,0.823529,0.396250,0.649353,0.364299,0.487179,0.333333,0.000000,0,1.0,0.0,0.0,0.0,1.0

In [51]:
from sklearn.model_selection import train_test_split
x=df.drop('LoanApproved',axis=1)
y=df['LoanApproved']

In [52]:
x_test,x_train,y_test,y_train=train_test_split(x,y,test_size=0.2,random_state=42)

In [53]:
from sklearn.tree import DecisionTreeClassifier,DecisionTreeRegressor

In [54]:
dtc=DecisionTreeClassifier()
dtc

DecisionTreeClassifier()

In [55]:
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [56]:
y_pred=dtc.predict(x_test)

In [57]:
y_pred

array([0, 1, 1, ..., 0, 1, 1], shape=(4000,))

In [58]:
from sklearn.metrics import classification_report
class_report=classification_report(y_test,y_pred)

In [60]:
print(class_report)

              precision    recall  f1-score   support

           0       0.95      0.95      0.95      3074
           1       0.83      0.83      0.83       926

    accuracy                           0.92      4000
   macro avg       0.89      0.89      0.89      4000
weighted avg       0.92      0.92      0.92      4000

In [61]:
dtr=DecisionTreeRegressor()
dtr

DecisionTreeRegressor()

In [62]:
dtr.fit(x_test,y_test)

DecisionTreeRegressor()

In [63]:
y_pred=dtr.predict(x_test)
print(y_pred)

[0. 1. 1. ... 0. 0. 1.]

In [64]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,root_mean_squared_error
r2=r2_score(y_test,y_pred)
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=root_mean_squared_error(y_test,y_pred)

In [66]:
print('r2=',r2)
print('mae=',mae)
print('mse=',mse)
print('rmse=',rmse)

r2= 1.0
mae= 0.0
mse= 0.0
rmse= 0.0

In [67]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr

LogisticRegression()

In [68]:
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
y_pred

array([0, 1, 0, ..., 0, 0, 0], shape=(4000,))

In [69]:
from sklearn.metrics import classification_report
class_report=classification_report(y_test,y_pred)

In [70]:
print(class_report)

              precision    recall  f1-score   support

           0       0.90      0.95      0.92      3074
           1       0.79      0.66      0.72       926

    accuracy                           0.88      4000
   macro avg       0.85      0.80      0.82      4000
weighted avg       0.88      0.88      0.88      4000

In [71]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr

LinearRegression()

In [72]:
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)
y_pred

array([ 0.3050726 ,  0.6652283 ,  0.46970371, ..., -0.01098609,
        0.36725439,  0.46057317], shape=(4000,))

In [73]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score,root_mean_squared_error
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
rmse=root_mean_squared_error(y_test,y_pred)

In [74]:
print('mae=',mae)
print('mse=',mse)
print('r2=',r2)
print('rmse=',rmse)

mae= 0.2791769450067022
mse= 0.1134399827272462
r2= 0.362366267196082
rmse= 0.33680852531853495